# Generated by Django 2.2.2 on 2019-06-29 19:36

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descrição')),
                ('adicionais', models.ManyToManyField(related_name='categorias', to='core.Adicional')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponivel', models.BooleanField(default=True, null=True, verbose_name='Disponível')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Preço')),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Detalhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=400, verbose_name='Observação')),
                ('quantidade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baixa', models.BooleanField(default=False)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='core.Mesa')),
                ('pedido_detalhe', models.ManyToManyField(related_name='pedidos', to='core.Pedido_Detalhe')),
            ],
        ),
    ]
